// <auto-generated />
using System;
using Esx.Integration.CarRenal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Esx.Integration.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    [Migration("20250324042837_WithExtrTrial")]
    partial class WithExtrTrial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Esx.Domain.AuditTrailEntity.AuditTrail<Esx.Domain.AuditTrailEntity.DocumentExtra>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("DocumentAuditTrail", (string)null);
                });

            modelBuilder.Entity("Esx.Domain.AuditTrailEntity.AuditTrial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("AuditTrail", (string)null);
                });

            modelBuilder.Entity("Esx.Domain.CarEntity.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pice")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Esx.Domain.CustomerEntity.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DriverLicense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Esx.Domain.ReservationEntity.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Esx.Domain.AuditTrailEntity.AuditTrail<Esx.Domain.AuditTrailEntity.DocumentExtra>", b =>
                {
                    b.OwnsOne("Esx.Domain.AuditTrailEntity.AuditRecord", "Record", b1 =>
                        {
                            b1.Property<int>("AuditTrailId")
                                .HasColumnType("int");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("Changes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("DateCompleted")
                                .HasColumnType("datetime2");

                            b1.Property<int>("ObjectId")
                                .HasColumnType("int");

                            b1.Property<string>("ObjectName")
                                .IsRequired()
                                .HasMaxLength(2147483647)
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AuditTrailId");

                            b1.ToTable("DocumentAuditTrail");

                            b1.WithOwner()
                                .HasForeignKey("AuditTrailId");

                            b1.OwnsOne("Esx.Domain.AuditTrailEntity.UserInfo", "CompletedBy", b2 =>
                                {
                                    b2.Property<int>("AuditRecordAuditTrailId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Email")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)")
                                        .HasColumnName("CompletedByEmail");

                                    b2.Property<string>("UserName")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)")
                                        .HasColumnName("CompletedByUserName");

                                    b2.HasKey("AuditRecordAuditTrailId");

                                    b2.ToTable("DocumentAuditTrail");

                                    b2.WithOwner()
                                        .HasForeignKey("AuditRecordAuditTrailId");
                                });

                            b1.Navigation("CompletedBy")
                                .IsRequired();
                        });

                    b.OwnsOne("Esx.Domain.AuditTrailEntity.DocumentExtra", "Extra", b1 =>
                        {
                            b1.Property<int>("AuditTrailId")
                                .HasColumnType("int");

                            b1.Property<int>("Document")
                                .HasColumnType("int")
                                .HasColumnName("DocumentId");

                            b1.HasKey("AuditTrailId");

                            b1.ToTable("DocumentAuditTrail");

                            b1.WithOwner()
                                .HasForeignKey("AuditTrailId");
                        });

                    b.Navigation("Extra")
                        .IsRequired();

                    b.Navigation("Record")
                        .IsRequired();
                });

            modelBuilder.Entity("Esx.Domain.AuditTrailEntity.AuditTrial", b =>
                {
                    b.OwnsOne("Esx.Domain.AuditTrailEntity.AuditRecord", "Record", b1 =>
                        {
                            b1.Property<int>("AuditTrialId")
                                .HasColumnType("int");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("Changes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("DateCompleted")
                                .HasColumnType("datetime2");

                            b1.Property<int>("ObjectId")
                                .HasColumnType("int");

                            b1.Property<string>("ObjectName")
                                .IsRequired()
                                .HasMaxLength(2147483647)
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AuditTrialId");

                            b1.ToTable("AuditTrail");

                            b1.WithOwner()
                                .HasForeignKey("AuditTrialId");

                            b1.OwnsOne("Esx.Domain.AuditTrailEntity.UserInfo", "CompletedBy", b2 =>
                                {
                                    b2.Property<int>("AuditRecordAuditTrialId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Email")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)")
                                        .HasColumnName("CompletedByEmail");

                                    b2.Property<string>("UserName")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)")
                                        .HasColumnName("CompletedByUserName");

                                    b2.HasKey("AuditRecordAuditTrialId");

                                    b2.ToTable("AuditTrail");

                                    b2.WithOwner()
                                        .HasForeignKey("AuditRecordAuditTrialId");
                                });

                            b1.Navigation("CompletedBy")
                                .IsRequired();
                        });

                    b.Navigation("Record")
                        .IsRequired();
                });

            modelBuilder.Entity("Esx.Domain.CustomerEntity.Customer", b =>
                {
                    b.OwnsOne("Esx.Domain.CustomerEntity.PaymentInfo", "PaymentInfo", b1 =>
                        {
                            b1.Property<int>("CustomerId")
                                .HasColumnType("int");

                            b1.Property<int>("PreferedMethod")
                                .HasColumnType("int")
                                .HasColumnName("PaymentMethod");

                            b1.Property<bool>("Verified")
                                .HasColumnType("bit")
                                .HasColumnName("PaymentVerified");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("Esx.Domain.CustomerEntity.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("CustomerId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LastName");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PaymentInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Esx.Domain.ReservationEntity.Reservation", b =>
                {
                    b.HasOne("Esx.Domain.CustomerEntity.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
