// <auto-generated />
using System;
using Esx.Integration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Esx.Integration.Migrations
{
    [DbContext(typeof(MemoryDbContext))]
    partial class MemoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cars")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Esx.Domain.Entities.RentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AdditionalFees")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("AdditionalServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarLicensePlate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cleanliness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerExpirience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRent")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriversLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DropoffDamages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DropoffFuelLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DropoffLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DropoffMileage")
                        .HasColumnType("int");

                    b.Property<string>("InsuranceChoice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsRoadReady")
                        .HasColumnType("bit");

                    b.Property<bool?>("PameymentConfirmation")
                        .HasColumnType("bit");

                    b.Property<string>("PickupDamages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupFuelLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PickupMileage")
                        .HasColumnType("int");

                    b.Property<int?>("RentDuration")
                        .HasColumnType("int");

                    b.Property<string>("RentalTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceImprovementOpportunities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SignedByCustomer")
                        .HasColumnType("bit");

                    b.Property<string>("TireCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalCharges")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("UpsoldServices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleClass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RentRecord", "cars");
                });
#pragma warning restore 612, 618
        }
    }
}
